version: '3.8'

services:
  sewvana-db:
    image: mysql:8.0
    container_name: sewvana_mysql
    restart: always
    environment:
      MYSQL_DATABASE: sewvana_db
      MYSQL_USER: sewvana_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - sewvana_db_data:/var/lib/mysql
      - ./src/main/resources/db:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: sewvana_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  sewvana_db_data: